### ISSUE TITLE
No Docker image for linto-platform-stt-standalone-worker:online

### ISSUE THREAD

**Issue by jbleduigou** [linto-ai/linto-platform-stack#6] opened 2020-07-29 15:08 UTC
There seems to be an error in the script startup.sh :

The following command does not match a valid image tag:
```
docker pull lintoai/linto-platform-stt-standalone-worker:online
```
Output is:
```
Error response from daemon: manifest for lintoai/linto-platform-stt-standalone-worker:online not found: manifest unknown: manifest unknown
```

I can see two ways of fixing that:
 - remove the command alltogether
 - push the image to the public docker registry

**Comment by damienlaine** [comment] 2020-07-30 08:52
@irebai : Can you check this ?
@jbleduigou : You can strip this line out of the deployment script until we fix the docker hub image. Anyway the online transcription service (streaming) is not used in the platform at the moment.

**Comment by irebai** [comment] 2020-07-30 09:51
#> @irebai : Can you check this ?
> @jbleduigou : You can strip this line out of the deployment script until we fix the docker hub image. Anyway the online transcription service (streaming) is not used in the platform at the moment.

@damienlaine @jbleduigou : the issue is now fixed. I have pulled the image on docker hub.

**Closed by irebai** 2020-07-30 09:51 UTC

**Comment by jbleduigou** [comment] 2020-07-30 10:06
Thanks @irebai!
It is working fine now.
